
import { WordForms } from '../types';

export const WORD_LIST: WordForms[] = [
  // User provided list (Unit 1-8)
  { base: 'local', noun: ['local', 'locality', 'localization'], verb: 'localize', adjective: 'local', adverb: 'locally' },
  { base: 'community', noun: 'community', verb: 'commune', adjective: 'communal', adverb: 'communally' },
  { base: 'volunteer', noun: 'volunteer', verb: 'volunteer', adjective: 'voluntary', adverb: 'voluntarily' },
  { base: 'charity', noun: 'charity', verb: 'charitise', adjective: 'charitable', adverb: 'charitably' },
  { base: 'donate', noun: ['donation', 'donor'], verb: 'donate', adjective: 'donated' },
  { base: 'organization', noun: 'organization', verb: 'organize', adjective: 'organizational', adverb: 'organizationally' },
  { base: 'event', noun: 'event', adjective: 'eventful' },
  { base: 'support', noun: ['support', 'supporter'], verb: 'support', adjective: 'supportive', adverb: 'supportively' },
  { base: 'participate', noun: ['participation', 'participant'], verb: 'participate', adjective: 'participatory' },
  { base: 'benefit', noun: 'benefit', verb: 'benefit', adjective: 'beneficial', adverb: 'beneficially' },
  { base: 'campaign', noun: 'campaign', verb: 'campaign' },
  { base: 'neighbor', noun: ['neighbor', 'neighborhood'], verb: 'neighbor', adjective: 'neighborly' },
  { base: 'improve', noun: 'improvement', verb: 'improve', adjective: 'improved' },
  { base: 'environment', noun: 'environment', adjective: 'environmental', adverb: 'environmentally' },
  { base: 'cooperation', noun: 'cooperation', verb: 'cooperate', adjective: 'cooperative', adverb: 'cooperatively' },
  { base: 'urban', noun: 'urbanization', verb: 'urbanize', adjective: 'urban' },
  { base: 'skyscraper', noun: 'skyscraper' },
  { base: 'metropolitan', noun: 'metropolis', adjective: 'metropolitan' },
  { base: 'infrastructure', noun: 'infrastructure', adjective: 'infrastructural' },
  { base: 'congestion', noun: 'congestion', verb: 'congest', adjective: 'congested' },
  { base: 'transport', noun: 'transport', verb: 'transport' },
  { base: 'pedestrian', noun: 'pedestrian', adjective: 'pedestrian' },
  { base: 'cosmopolitan', noun: 'cosmopolitan', adjective: 'cosmopolitan' },
  { base: 'pollution', noun: 'pollution', verb: 'pollute', adjective: 'polluted' },
  { base: 'nightlife', noun: 'nightlife' },
  { base: 'convenience', noun: 'convenience', adjective: 'convenient', adverb: 'conveniently' },
  { base: 'vibrant', noun: 'vibrancy', adjective: 'vibrant', adverb: 'vibrantly' },
  { base: 'affordable', noun: 'affordability', verb: 'afford', adjective: 'affordable', adverb: 'affordably' },
  { base: 'estate', noun: 'estate' },
  { base: 'suburban', noun: 'suburb', adjective: 'suburban' },
  { base: 'nutrition', noun: 'nutrition', adjective: 'nutritious', adverb: 'nutritiously' },
  { base: 'balance', noun: 'balance', verb: 'balance', adjective: 'balanced' },
  { base: 'workout', noun: 'workout', verb: 'work out' },
  { base: 'mental', adjective: 'mental', adverb: 'mentally' },
  { base: 'obesity', noun: 'obesity', adjective: 'obese' },
  { base: 'calorie', noun: 'calorie', adjective: 'caloric' },
  { base: 'hydration', noun: 'hydration', verb: 'hydrate', adjective: 'hydrated' },
  { base: 'exercise', noun: 'exercise', verb: 'exercise' },
  { base: 'junk food', noun: 'junk food' },
  { base: 'self-care', noun: 'self-care' },
  { base: 'mindfulness', noun: 'mindfulness', adjective: 'mindful', adverb: 'mindfully' },
  { base: 'stress', noun: 'stress', verb: 'stress', adjective: 'stressful', adverb: 'stressfully' },
  { base: 'immune', noun: 'immunity', verb: 'immunize', adjective: 'immune' },
  { base: 'strength', noun: 'strength', verb: 'strengthen', adjective: 'strong', adverb: 'strongly' },
  { base: 'habit', noun: 'habit', adjective: 'habitual', adverb: 'habitually' },
  { base: 'ancestor', noun: 'ancestor', adjective: 'ancestral' },
  { base: 'historical', noun: 'history', adjective: 'historical', adverb: 'historically' },
  { base: 'tradition', noun: 'tradition', adjective: 'traditional', adverb: 'traditionally' },
  { base: 'heritage', noun: 'heritage' },
  { base: 'artifact', noun: 'artifact' },
  { base: 'nostalgia', noun: 'nostalgia', adjective: 'nostalgic', adverb: 'nostalgically' },
  { base: 'handwritten', adjective: 'handwritten' },
  { base: 'storytelling', noun: 'storytelling' },
  { base: 'vintage', noun: 'vintage', adjective: 'vintage' },
  { base: 'legend', noun: 'legend', adjective: 'legendary' },
  { base: 'folk tale', noun: 'folk tale' },
  { base: 'commemorate', noun: 'commemoration', verb: 'commemorate', adjective: 'commemorative' },
  { base: 'relic', noun: 'relic' },
  { base: 'manuscript', noun: 'manuscript' },
  { base: 'ancient', adjective: 'ancient' },
  { base: 'adventure', noun: 'adventure', verb: 'adventure', adjective: 'adventurous', adverb: 'adventurously' },
  { base: 'challenge', noun: 'challenge', verb: 'challenge', adjective: 'challenging' },
  { base: 'accomplishment', noun: 'accomplishment', verb: 'accomplish', adjective: 'accomplished' },
  { base: 'unforgettable', adjective: 'unforgettable', adverb: 'unforgettably' },
  { base: 'obstacle', noun: 'obstacle' },
  { base: 'lesson', noun: 'lesson' },
  { base: 'memory', noun: 'memory', verb: 'memorize', adjective: 'memorable', adverb: 'memorably' },
  { base: 'journey', noun: 'journey', verb: 'journey' },
  { base: 'milestone', noun: 'milestone' },
  { base: 'fear', noun: 'fear', verb: 'fear', adjective: 'fearful', adverb: 'fearfully' },
  { base: 'overcome', verb: 'overcome' },
  { base: 'resilience', noun: 'resilience', adjective: 'resilient' },
  { base: 'wisdom', noun: 'wisdom', adjective: 'wise', adverb: 'wisely' },
  { base: 'growth', noun: 'growth', verb: 'grow', adjective: 'growing' },
  { base: 'inspiration', noun: 'inspiration', verb: 'inspire', adjective: 'inspirational', adverb: 'inspirationally' },
  { base: 'lifestyle', noun: 'lifestyle' },
  { base: 'generation', noun: 'generation', verb: 'generate', adjective: 'generational' },
  { base: 'transformation', noun: 'transformation', verb: 'transform', adjective: 'transformative' },
  { base: 'modernization', noun: 'modernization', verb: 'modernize', adjective: 'modern' },
  { base: 'rural', adjective: 'rural' },
  { base: 'urbanization', noun: 'urbanization', verb: 'urbanize', adjective: 'urban' },
  { base: 'housing', noun: 'housing', verb: 'house' },
  { base: 'transportation', noun: 'transportation', verb: 'transport' },
  { base: 'cultural', noun: 'culture', adjective: 'cultural', adverb: 'culturally' },
  { base: 'attire', noun: 'attire' },
  { base: 'progress', noun: 'progress', verb: 'progress', adjective: 'progressive', adverb: 'progressively' },
  { base: 'technology', noun: 'technology', adjective: 'technological', adverb: 'technologically' },
  { base: 'family values', noun: 'family values' },
  { base: 'occupation', noun: 'occupation', verb: 'occupy', adjective: 'occupational' },
  { base: 'wonder', noun: 'wonder', verb: 'wonder', adjective: 'wonderful', adverb: 'wonderfully' },
  { base: 'landscape', noun: 'landscape' },
  { base: 'breathtaking', adjective: 'breathtaking', adverb: 'breathtakingly' },
  { base: 'conservation', noun: ['conservation', 'conservationist'], verb: 'conserve', adjective: 'conservative' },
  { base: 'ecosystem', noun: 'ecosystem' },
  { base: 'erosion', noun: 'erosion', verb: 'erode' },
  { base: 'wildlife', noun: 'wildlife' },
  { base: 'tropical', adjective: 'tropical', adverb: 'tropically' },
  { base: 'marine', adjective: 'marine' },
  { base: 'volcano', noun: 'volcano', adjective: 'volcanic' },
  { base: 'cave', noun: 'cave' },
  { base: 'waterfall', noun: 'waterfall' },
  { base: 'coral reef', noun: 'coral reef' },
  { base: 'biodiversity', noun: 'biodiversity', adjective: 'biodiverse' },
  { base: 'tourism', noun: 'tourism', adjective: 'touristic' },
  { base: 'destination', noun: 'destination' },
  { base: 'accommodation', noun: 'accommodation', verb: 'accommodate', adjective: 'accommodating' },
  { base: 'itinerary', noun: 'itinerary' },
  { base: 'sightseeing', noun: 'sightseeing' },
  { base: 'souvenir', noun: 'souvenir' },
  { base: 'hospitality', noun: 'hospitality', adjective: 'hospitable', adverb: 'hospitably' },
  { base: 'travel agency', noun: 'travel agency' },
  { base: 'eco-tourism', noun: 'eco-tourism' },
  { base: 'package tour', noun: 'package tour' },
  { base: 'local cuisine', noun: 'local cuisine' },
  { base: 'budget travel', noun: 'budget travel' },
  { base: 'backpacker', noun: 'backpacker' },
  { base: 'cultural exchange', noun: 'cultural exchange' },
  
  // Additional words to reach 200
  { base: 'beauty', noun: 'beauty', verb: 'beautify', adjective: 'beautiful', adverb: 'beautifully' },
  { base: 'danger', noun: 'danger', verb: 'endanger', adjective: 'dangerous', adverb: 'dangerously' },
  { base: 'success', noun: 'success', verb: 'succeed', adjective: 'successful', adverb: 'successfully' },
  { base: 'happy', noun: 'happiness', adjective: 'happy', adverb: 'happily' },
  { base: 'friend', noun: ['friend', 'friendship'], adjective: 'friendly' },
  { base: 'nation', noun: ['nation', 'nationality'], verb: 'nationalize', adjective: 'national', adverb: 'nationally' },
  { base: 'music', noun: ['music', 'musician'], adjective: 'musical', adverb: 'musically' },
  { base: 'art', noun: ['art', 'artist'], adjective: 'artistic', adverb: 'artistically' },
  { base: 'science', noun: ['science', 'scientist'], adjective: 'scientific', adverb: 'scientifically' },
  { base: 'economy', noun: ['economy', 'economist'], verb: 'economize', adjective: 'economic', adverb: 'economically' },
  { base: 'politics', noun: ['politics', 'politician'], adjective: 'political', adverb: 'politically' },
  { base: 'health', noun: 'health', adjective: 'healthy', adverb: 'healthily' },
  { base: 'industry', noun: 'industry', adjective: 'industrial', adverb: 'industrially' },
  { base: 'communicate', noun: 'communication', verb: 'communicate', adjective: 'communicative' },
  { base: 'educate', noun: 'education', verb: 'educate', adjective: 'educational', adverb: 'educationally' },
  { base: 'create', noun: ['creation', 'creator', 'creativity'], verb: 'create', adjective: 'creative', adverb: 'creatively' },
  { base: 'decide', noun: 'decision', verb: 'decide', adjective: 'decisive', adverb: 'decisively' },
  { base: 'act', noun: ['action', 'actor', 'activity'], verb: 'act', adjective: 'active', adverb: 'actively' },
  { base: 'differ', noun: 'difference', verb: 'differ', adjective: 'different', adverb: 'differently' },
  { base: 'depend', noun: ['dependence', 'dependency'], verb: 'depend', adjective: 'dependent', adverb: 'dependently' },
  { base: 'peace', noun: 'peace', adjective: 'peaceful', adverb: 'peacefully' },
  { base: 'care', noun: 'care', verb: 'care', adjective: 'careful', adverb: 'carefully' },
  { base: 'hope', noun: 'hope', verb: 'hope', adjective: 'hopeful', adverb: 'hopefully' },
  { base: 'use', noun: ['use', 'user'], verb: 'use', adjective: ['useful', 'useless'], adverb: 'usefully' },
  { base: 'help', noun: 'help', verb: 'help', adjective: ['helpful', 'helpless'], adverb: 'helpfully' },
  { base: 'power', noun: 'power', verb: 'empower', adjective: 'powerful', adverb: 'powerfully' },
  { base: 'comfort', noun: 'comfort', verb: 'comfort', adjective: 'comfortable', adverb: 'comfortably' },
  { base: 'fashion', noun: 'fashion', adjective: 'fashionable', adverb: 'fashionably' },
  { base: 'reason', noun: 'reason', verb: 'reason', adjective: 'reasonable', adverb: 'reasonably' },
  { base: 'nature', noun: 'nature', adjective: 'natural', adverb: 'naturally' },
  { base: 'fame', noun: 'fame', adjective: 'famous' },
  { base: 'courage', noun: 'courage', verb: 'encourage', adjective: 'courageous', adverb: 'courageously' },
  { base: 'able', noun: 'ability', adjective: 'able' },
  { base: 'possible', noun: 'possibility', adjective: 'possible', adverb: 'possibly' },
  { base: 'important', noun: 'importance', adjective: 'important', adverb: 'importantly' },
  { base: 'real', noun: ['reality', 'realism'], verb: 'realize', adjective: 'real', adverb: 'really' },
  { base: 'simple', noun: 'simplicity', verb: 'simplify', adjective: 'simple', adverb: 'simply' },
  { base: 'quick', verb: 'quicken', adjective: 'quick', adverb: 'quickly' },
  { base: 'slow', verb: 'slow', adjective: 'slow', adverb: 'slowly' },
  { base: 'loud', noun: 'loudness', adjective: 'loud', adverb: 'loudly' },
  { base: 'soft', noun: 'softness', verb: 'soften', adjective: 'soft', adverb: 'softly' },
  { base: 'safe', noun: 'safety', adjective: 'safe', adverb: 'safely' },
  { base: 'protect', noun: 'protection', verb: 'protect', adjective: 'protective', adverb: 'protectively' },
  { base: 'inform', noun: ['information', 'informant'], verb: 'inform', adjective: 'informative' },
  { base: 'compete', noun: ['competition', 'competitor'], verb: 'compete', adjective: 'competitive', adverb: 'competitively' },
  { base: 'attract', noun: 'attraction', verb: 'attract', adjective: 'attractive', adverb: 'attractively' },
  { base: 'admire', noun: 'admiration', verb: 'admire', adjective: 'admirable', adverb: 'admirably' },
  { base: 'impress', noun: 'impression', verb: 'impress', adjective: 'impressive', adverb: 'impressively' },
  { base: 'popular', noun: 'popularity', adjective: 'popular', adverb: 'popularly' },
  { base: 'connect', noun: 'connection', verb: 'connect', adjective: 'connected' },
  { base: 'collect', noun: ['collection', 'collector'], verb: 'collect', adjective: 'collective', adverb: 'collectively' },
  { base: 'excite', noun: 'excitement', verb: 'excite', adjective: 'exciting', adverb: 'excitingly' },
  { base: 'entertain', noun: 'entertainment', verb: 'entertain', adjective: 'entertaining' },
  { base: 'imagine', noun: 'imagination', verb: 'imagine', adjective: 'imaginative', adverb: 'imaginatively' },
  { base: 'invent', noun: ['invention', 'inventor'], verb: 'invent', adjective: 'inventive' },
  { base: 'explore', noun: ['exploration', 'explorer'], verb: 'explore', adjective: 'exploratory' },
  { base: 'pollute', noun: 'pollution', verb: 'pollute', adjective: 'polluted' },
  { base: 'destroy', noun: 'destruction', verb: 'destroy', adjective: 'destructive', adverb: 'destructively' },
  { base: 'construct', noun: 'construction', verb: 'construct', adjective: 'constructive', adverb: 'constructively' },
  { base: 'produce', noun: ['production', 'producer', 'product'], verb: 'produce', adjective: 'productive', adverb: 'productively' },
  { base: 'consume', noun: ['consumption', 'consumer'], verb: 'consume', adjective: 'consumable' },
  { base: 'advise', noun: ['advice', 'adviser'], verb: 'advise', adjective: 'advisable' },
  { base: 'agree', noun: 'agreement', verb: 'agree', adjective: 'agreeable' },
  { base: 'believe', noun: 'belief', verb: 'believe', adjective: 'believable' },
  { base: 'choose', noun: 'choice', verb: 'choose', adjective: 'chosen' },
  { base: 'live', noun: 'life', verb: 'live', adjective: 'alive' },
  { base: 'die', noun: 'death', verb: 'die', adjective: 'dead' },
  { base: 'speak', noun: ['speech', 'speaker'], verb: 'speak', adjective: 'spoken' },
  { base: 'think', noun: 'thought', verb: 'think', adjective: 'thoughtful' },
  { base: 'know', noun: 'knowledge', verb: 'know', adjective: 'knowledgeable' },
  { base: 'conclude', noun: 'conclusion', verb: 'conclude', adjective: 'conclusive' },
  { base: 'explain', noun: 'explanation', verb: 'explain', adjective: 'explanatory' },
  { base: 'solve', noun: 'solution', verb: 'solve', adjective: 'solvable' },
  { base: 'respond', noun: 'response', verb: 'respond', adjective: 'responsive' },
  { base: 'strong', noun: 'strength', verb: 'strengthen', adjective: 'strong', adverb: 'strongly' },
  { base: 'weak', noun: 'weakness', verb: 'weaken', adjective: 'weak' },
  { base: 'wide', noun: 'width', verb: 'widen', adjective: 'wide', adverb: 'widely' },
  { base: 'long', noun: 'length', verb: 'lengthen', adjective: 'long' },
  { base: 'high', noun: 'height', verb: 'heighten', adjective: 'high', adverb: 'highly' },
  { base: 'deep', noun: 'depth', verb: 'deepen', adjective: 'deep', adverb: 'deeply' },
  { base: 'poor', noun: 'poverty', adjective: 'poor' },
  { base: 'rich', noun: 'riches', verb: 'enrich', adjective: 'rich' },
  { base: 'free', noun: 'freedom', verb: 'free', adjective: 'free', adverb: 'freely' },
  { base: 'true', noun: 'truth', adjective: 'true', adverb: 'truly' },
  { base: 'wise', noun: 'wisdom', adjective: 'wise', adverb: 'wisely' },
  { base: 'brave', noun: 'bravery', adjective: 'brave', adverb: 'bravely' },
  { base: 'honest', noun: 'honesty', adjective: 'honest', adverb: 'honestly' },
  { base: 'curious', noun: 'curiosity', adjective: 'curious', adverb: 'curiously' },
  { base: 'generous', noun: 'generosity', adjective: 'generous', adverb: 'generously' },
  { base: 'loyal', noun: 'loyalty', adjective: 'loyal', adverb: 'loyally' },
  { base: 'patient', noun: 'patience', adjective: 'patient', adverb: 'patiently' },
];
